name: Build README

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        make init
    - name: Update README
      env:
        ENV: release
      run: |
        make build
        cat README.md
    - name: Commit and push if changed
      env:
        COMMIT_MSG: Update README.md
        AUTHOR: v1siuol-bot
        EMAIL: lvzh.louis2013@gmail.com
      run: |
        git config --global user.email $EMAIL
        git config --global user.name $AUTHOR
        git diff
        git pull origin main
        git add -A
        git commit -m "$COMMIT_MSG" || exit 0
        git push origin main
